package com.yozyyy.composeplaytime

data class MovieItem(val name: String, val resId: Int, val description: String = "")

val movieData = arrayOf(
    MovieItem("Robot Dreams", R.drawable.robot_dreams, "DOG lives in Manhattan and he's tired of being alone. One day he decides to build himself a robot, a companion. Their friendship blossoms, until they become inseparable, to the rhythm of 80's NYC. One summer night, DOG, with great sadness, is forced to abandon ROBOT at the beach. Will they ever meet again?"),
    MovieItem("Anatomy of a Fall", R.drawable.anatomy_of_a_fall, description = "The story begins when Samuel is found dead in the snow outside the isolated chalet where he lived with his wife Sandra, a German writer, and their partially-sighted 11-year-old son Daniel. An investigation leads to a conclusion of \"suspicious death\": it's impossible to know for sure whether he took his own life or was killed. Sandra is indicted, and we follow her trial which pulls the couple's relationship apart. Daniel is caught in the middle: between the trial and their home life, doubts take their toll on the mother-son relationship."),
    MovieItem("Frances Ha", R.drawable.frances_ha, description = "Frances lives in New York, but she doesn't really have an apartment. Frances is an apprentice for a dance company, but she's not really a dancer. Frances has a best friend named Sophie, but they aren't really speaking anymore. Frances throws herself headlong into her dreams, even as their possible reality dwindles. Frances wants so much more than she has but lives her life with unaccountable joy and lightness."),
    MovieItem("Pulp Fiction", R.drawable.pulp_fiction, description = "Jules Winnfield (Samuel L. Jackson) and Vincent Vega (John Travolta) are two hitmen who are out to retrieve a suitcase stolen from their employer, mob boss Marsellus Wallace (Ving Rhames). Wallace has also asked Vincent to take his wife Mia (Uma Thurman) out a few days later when Wallace himself will be out of town. Butch Coolidge (Bruce Willis) is an aging boxer who is paid by Wallace to lose his fight. The lives of these seemingly unrelated people are woven together comprising of a series of funny, bizarre and uncalled-for incidents."),
    MovieItem("The Shining", R.drawable.shining, description = "After landing a job as an off-season caretaker, Jack Torrance, an aspiring author and recovering alcoholic, drags his wife Wendy and gifted son Danny to snow-covered Colorado's secluded Overlook Hotel. However, writer's block prevents Jack from pursuing a new writing career. Everything has its time, however. First, the manager must give Jack a grand tour. Then, Mr Hallorann, the facility's aging chef, chats with Danny about rare psychic gifts. The mysterious employee also warns the boy about the cavernous hotel's abandoned rooms. Room 237, especially, is off-limits. That's all very well, but Jack is gradually losing his mind. After all, strange occurrences and blood-chilling visions have trapped the family in a silent gargantuan prison hammered by endless snowstorms. And now, incessant voices inside Jack's head demand sacrifice. However, is Jack capable of murder?"),
)
